name: my-first-workflow
# To trigger on any push to this repo in any branch.
on: 
  # Put trigger on next line (after on:) and with colon if more than one.
  push:
  schedule:
     # Execute every 5 minutes.
    - cron: "5 * * * *"
  # This trigger allows for manual execution.
  workflow_dispatch: 

# Jobs are executed in parallel.
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    # Steps are executed in sequence.
    steps: 
    - name: Step-1
      run: |
        pwd 
        ls -ltr
        hostname
    - name: Step-2 - Checkout
      uses: actions/checkout@v7.0.1
    - name: Step-3
      runs: |
        pwd
        ls -ltr
        hostname
    
  
   
    steps:
    - name: Job with multiple dependencies.
      run: sleep 10
    - name: Check runner.
      run: sw_vers
