name: my-first-workflow
# To trigger on any push to this repo in any branch.
on: push

# Jobs are executed in parallel.
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    # Steps are executed in sequence.
    steps: 
    - name: Running Single Command in Job1
      run: echo "This is my first GitHub workflow."
    - name: Checking OS release for GitHub hosted runner.
      run: cat /etc/os-release
    - name: Calling sleep.
      run: sleep 20
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
    - name: Checking the host name for runner.
      run: hostname
    - name: Running multiple commands.
      # Use pipe, then go to next line for multiple commmands, indent commands.
      run: |
        echo "Hi from okeeman"
        echo "Current time is `date`"
        sleep 20
  job3:
    name: JOB3
    # Triggered when job1 is completed.
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Job with single dependency.
      run: sleep 10
  job4:
    name: JOB4
    needs: [job1,job2,job3]
    runs-on: ubuntu-latest
    steps:
    - name: Job with multiple dependencies.
      run: sleep 10
